import type { Metadata } from 'next';
import { Roboto } from 'next/font/google'; // Importando a fonte Roboto
import './globals.css';
import Header from '@/components/header';
import QueryProvider from '@/utils/queryProvider';
import { cn } from '@/lib/utils';
import SessionProviderWrapper from '@/utils/sessionsProviderWrapper';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
	title: 'Transport Manager',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={cn('antialiased bg-gray-100', roboto.className)}>
				<SessionProviderWrapper>
					<QueryProvider>{children}</QueryProvider>
				</SessionProviderWrapper>
			</body>
		</html>
	);
}
